Fix `remi-fs` dev dependency causing This was causing the following error in CI:
error[E0464]: multiple candidates for  dependency  found
  --> src/avatars.rs:20:5
   |
20 | use remi_fs::default_resolver;
   |     ^^^^^^^
   |
   = note: candidate #1: /home/runner/work/charted/charted/target/debug/deps/libremi_fs-09770a630059b70a.rlib
   = note: candidate #2: /home/runner/work/charted/charted/target/debug/deps/libremi_fs-8009454c240cb515.rlib